### ISSUE TITLE
Add support for t-shirt size estimations

### ISSUE THREAD

**Issue by slav** [jgraglia/Trello-Points#1]
Can you please add support for t-shirt size estimations. I.e. task is: xs, s, m, l, xl, xxl, or ? (for unknown)

Or at least support custom strings as part of estimations list.
Thank you.

**Comment by jgraglia** [comment]
Hi,
It's a cool idea! I'll try to add that!

Thx for your feedback,

https://trello.com/c/AYLNP65r

**Comment by jgraglia** [comment]
v 0.34 supports this! 
(extension is deployed  but not yet available in chrome web store.. need to wait few minutes)

For now, lists did not sum cards with text points. May be I could add a total like "My List (XS:2, L:4, XXL:2, 16/23)" for a list containing
2 cards tagged XS
4 cards taggerd L
2 cards tagged XXL
a number of cards vith numeric points, filter active, for a total of 16 points displayed out of 23

but that's another story...!
