### ISSUE TITLE
Cannot install via Chrome WebStore. 

### ISSUE THREAD

**Issue by ghost** [jgraglia/Trello-Points#2]
Chrome 19.0.1084.30 beta  Ubuntu 11.10

Thanks! :)

**Comment by jgraglia** [comment]
Hi, one of my dev box is running
   18.0.1025.162 (Build de développement 131933 Linux) Ubuntu 11.10
One other is a win box (but can't tell chrome version)

I will try to find the beta chrome version you are using and test the install.

Thx for the feedback!

Edit : found beta version ! https://www.google.com/landing/chrome/beta/

**Comment by jgraglia** [comment]
Ok bug reproduced with google chrome beta. Sth related to background page and manifest version.
see http://code.google.com/p/chromium/issues/detail?id=98537

Tip : error is more precise when trying to install extension as a "not packaged" extension

**Comment by jgraglia** [comment]
Found the pb : the "background" flag in the manifest. 

If I remove it, it works on chrome beta 19!... but that kill the communication between the options page and the extension in Chromium 18..
Argh, have to found how to detect the version of Chrome and use the appropriate manifest...

**Comment by ghost** [comment]
Thank you very much for your job! Now i'm back to chrome 18 stable... Just to use Trello-Points: i love it :). 
I use Trello-Points as a budget system for business planning. Imagine a list where Card "a" = (100) $ it is a revenue; and Card "b" (-40) $ it is a Cost. The sum is 60 and now, is correctly exposed in the title of the list. Trello-Points becames "Trello Budget" :). So, i try to use Trello-Points as a sort of spreadsheet. It's great! Please allow negative number... Actually, in the title list are exposed positive number only. Thanks! :)

**Comment by jgraglia** [comment]
Negative points are a missing feature. I will try to implement this soon...!

**Comment by ghost** [comment]
Great! :)

**Comment by slav** [comment]
Any word on fixing this? Extension stopped working after updating to Chromium 19

**Comment by ghost** [comment]
+1 Please :)

**Comment by jgraglia** [comment]
Hi guys! Sorry, I was quite occupied this weekend and last week... I'll try to work on this soon. Btw negative points are implemented;.. but not yet released...

**Comment by jgraglia** [comment]
Hi, new version 0.35 release yesterday. should correct that bug. Let me know if it is ok for you..

**Comment by slav** [comment]
Seems to work. Thank you!

**Comment by ghost** [comment]
Thank you!
